// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:io';

import 'package:crypto/crypto.dart' show sha256;

Future<void> main(List<String> args) async {
  final version = args.isNotEmpty ? args[0] : '0.6.2-wip';
  final httpClient = HttpClient();

  stdout.writeln('Fetching binary hashes for release tag v$version...');
  final hashes = <String, String>{};

  final targets = [
    ('linux', 'x64', 'libwebcrypto.so'),
    ('macOS', 'x64', 'libwebcrypto.dylib'),
    ('macOS', 'arm64', 'libwebcrypto.dylib'),
    ('windows', 'x64', 'webcrypto.dll'),
    ('android', 'arm64', 'libwebcrypto.so'),
    ('android', 'arm', 'libwebcrypto.so'),
    ('android', 'x64', 'libwebcrypto.so'),
    ('iOS', 'arm64', 'libwebcrypto.dylib'),
  ];

  for (final (os, arch, ext) in targets) {
    final targetTriple = '$os-$arch';
    final assetName = 'webcrypto-$targetTriple-$ext';
    final uri = Uri.parse(
      'https://github.com/google/webcrypto.dart/releases/download/v$version/$assetName',
    );

    stdout.writeln('Fetching $assetName from $uri...');
    try {
      final request = await httpClient.getUrl(uri);
      final response = await request.close();
      if (response.statusCode != 200) {
        stdout.writeln('  File not found (HTTP ${response.statusCode})');
        continue;
      }
      final bytes = await response.fold<List<int>>([], (a, b) => a..addAll(b));
      final fileHash = sha256.convert(bytes).toString();
      hashes[targetTriple] = fileHash;
      stdout.writeln('  Hash: $fileHash');
    } catch (e) {
      stdout.writeln('  Error: $e');
    }
  }
  httpClient.close(force: true);

  final buffer = StringBuffer();
  buffer.writeln('// Copyright 2025 Google LLC');
  buffer.writeln('//');
  buffer.writeln('// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`.');
  buffer.writeln('');
  buffer.writeln("const releaseVersion = '$version';");
  buffer.writeln('');
  buffer.writeln('const fileHashes = <String, String>{');
  for (final entry in hashes.entries) {
    buffer.writeln("  '${entry.key}': '${entry.value}',");
  }
  buffer.writeln('};');

  await File('lib/src/hook_helpers/hashes.dart').writeAsString(buffer.toString());
  stdout.writeln('Updated lib/src/hook_helpers/hashes.dart');
}
