// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`.

const releaseVersion = '0.6.2-wip';

const fileHashes = <String, String>{
  'linux-x64': '',
  'macOS-x64': '',
  'macOS-arm64': '',
  'windows-x64': '',
  'android-arm64': '',
  'android-arm': '',
  'android-x64': '',
  'iOS-arm64': '',
};
