// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ignore_for_file: unused_element
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Helper function to get the size of CBB structure for FFI allocation.
@ffi.Native<ffi.Size Function()>(
  symbol: 'webcrypto_get_CBB_size',
  assetId: 'package:webcrypto/webcrypto.dart',
)
external int webcrypto_get_CBB_size();

/// Helper function to retrieve the address of EVP_PKEY_free for NativeFinalizer.
@ffi.Native<ffi.Pointer<ffi.Void> Function()>(
  symbol: 'webcrypto_get_EVP_PKEY_free_address',
  assetId: 'package:webcrypto/webcrypto.dart',
)
external ffi.Pointer<ffi.Void> webcrypto_get_EVP_PKEY_free_address();
