/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// **GENERATED FILE DO NOT MODIFY**
//
// This file is generated from `src/symbols.yaml` using:
// `tool/generate_symbols_table.dart`

#include "symbols.h"

void* _webcrypto_symbol_table[] = {
    (void*)&webcrypto_dart_dl_initialize,
    (void*)&webcrypto_dart_dl_attach_finalizer,
    (void*)&BN_bin2bn,
    (void*)&BN_bn2bin_padded,
    (void*)&BN_free,
    (void*)&BN_new,
    (void*)&BN_num_bytes,
    (void*)&BN_set_word,
    (void*)&CBB_cleanup,
    (void*)&CBB_data,
    (void*)&CBB_flush,
    (void*)&CBB_init,
    (void*)&CBB_len,
    (void*)&CBB_zero,
    (void*)&CBS_init,
    (void*)&CRYPTO_memcmp,
    (void*)&ECDH_compute_key,
    (void*)&ECDSA_SIG_free,
    (void*)&ECDSA_SIG_get0,
    (void*)&ECDSA_SIG_marshal,
    (void*)&ECDSA_SIG_new,
    (void*)&ECDSA_SIG_parse,
    (void*)&EC_GROUP_get0_order,
    (void*)&EC_GROUP_get_curve_name,
    (void*)&EC_GROUP_get_degree,
    (void*)&EC_KEY_check_key,
    (void*)&EC_KEY_free,
    (void*)&EC_KEY_generate_key,
    (void*)&EC_KEY_get0_group,
    (void*)&EC_KEY_get0_private_key,
    (void*)&EC_KEY_get0_public_key,
    (void*)&EC_KEY_get_enc_flags,
    (void*)&EC_KEY_new_by_curve_name,
    (void*)&EC_KEY_set_enc_flags,
    (void*)&EC_KEY_set_private_key,
    (void*)&EC_KEY_set_public_key,
    (void*)&EC_KEY_set_public_key_affine_coordinates,
    (void*)&EC_POINT_free,
    (void*)&EC_POINT_get_affine_coordinates_GFp,
    (void*)&EC_POINT_new,
    (void*)&EC_POINT_oct2point,
    (void*)&EC_POINT_point2cbb,
    (void*)&ERR_clear_error,
    (void*)&ERR_error_string_n,
    (void*)&ERR_get_error,
    (void*)&ERR_peek_error,
    (void*)&EVP_aead_aes_128_gcm,
    (void*)&EVP_aead_aes_256_gcm,
    (void*)&EVP_AEAD_CTX_free,
    (void*)&EVP_AEAD_CTX_new,
    (void*)&EVP_AEAD_CTX_open,
    (void*)&EVP_AEAD_CTX_seal,
    (void*)&EVP_AEAD_max_overhead,
    (void*)&EVP_aes_128_cbc,
    (void*)&EVP_aes_128_ctr,
    (void*)&EVP_aes_256_cbc,
    (void*)&EVP_aes_256_ctr,
    (void*)&EVP_CIPHER_CTX_free,
    (void*)&EVP_CIPHER_CTX_new,
    (void*)&EVP_CipherFinal_ex,
    (void*)&EVP_CipherInit_ex,
    (void*)&EVP_CIPHER_iv_length,
    (void*)&EVP_CipherUpdate,
    (void*)&EVP_DigestFinal,
    (void*)&EVP_DigestInit,
    (void*)&EVP_DigestSignFinal,
    (void*)&EVP_DigestSignInit,
    (void*)&EVP_DigestSignUpdate,
    (void*)&EVP_DigestUpdate,
    (void*)&EVP_DigestVerifyFinal,
    (void*)&EVP_DigestVerifyInit,
    (void*)&EVP_DigestVerifyUpdate,
    (void*)&EVP_marshal_private_key,
    (void*)&EVP_marshal_public_key,
    (void*)&EVP_MD_CTX_free,
    (void*)&EVP_MD_CTX_new,
    (void*)&EVP_MD_CTX_size,
    (void*)&EVP_parse_private_key,
    (void*)&EVP_parse_public_key,
    (void*)&EVP_PKEY_CTX_free,
    (void*)&EVP_PKEY_CTX_new,
    (void*)&EVP_PKEY_CTX_set0_rsa_oaep_label,
    (void*)&EVP_PKEY_CTX_set_rsa_mgf1_md,
    (void*)&EVP_PKEY_CTX_set_rsa_oaep_md,
    (void*)&EVP_PKEY_CTX_set_rsa_padding,
    (void*)&EVP_PKEY_CTX_set_rsa_pss_saltlen,
    (void*)&EVP_PKEY_decrypt,
    (void*)&EVP_PKEY_decrypt_init,
    (void*)&EVP_PKEY_encrypt,
    (void*)&EVP_PKEY_encrypt_init,
    (void*)&EVP_PKEY_free,
    (void*)&EVP_PKEY_get1_EC_KEY,
    (void*)&EVP_PKEY_get1_RSA,
    (void*)&EVP_PKEY_id,
    (void*)&EVP_PKEY_new,
    (void*)&EVP_PKEY_set1_EC_KEY,
    (void*)&EVP_PKEY_set1_RSA,
    (void*)&EVP_sha1,
    (void*)&EVP_sha256,
    (void*)&EVP_sha384,
    (void*)&EVP_sha512,
    (void*)&HKDF,
    (void*)&HMAC_CTX_free,
    (void*)&HMAC_CTX_new,
    (void*)&HMAC_Final,
    (void*)&HMAC_Init_ex,
    (void*)&HMAC_size,
    (void*)&HMAC_Update,
    (void*)&OPENSSL_malloc,
    (void*)&PKCS5_PBKDF2_HMAC,
    (void*)&RAND_bytes,
    (void*)&RSA_check_key,
    (void*)&RSA_free,
    (void*)&RSA_generate_key_ex,
    (void*)&RSA_get0_crt_params,
    (void*)&RSA_get0_factors,
    (void*)&RSA_get0_key,
    (void*)&RSA_new,
    (void*)&RSAPublicKey_dup,
    (void*)&RSA_set0_crt_params,
    (void*)&RSA_set0_factors,
    (void*)&RSA_set0_key,
    (void*)&OPENSSL_free,
    (void*)&OPENSSL_memdup,
    (void*)&EVP_MD_size,
    (void*)&EVP_AEAD_nonce_length,
    (void*)&EVP_AEAD_max_tag_len,
    (void*)&EVP_AEAD_key_length,
    (void*)&BN_value_one,
    (void*)&BN_add,
    (void*)&BN_sub,
    (void*)&BN_cmp,
    (void*)&BN_lshift,
    (void*)&EVP_CIPHER_block_size,
    (void*)&EC_GROUP_new_by_curve_name,
    (void*)&EC_GROUP_free,
    (void*)&EVP_PKEY_set_type,
    (void*)&BORINGSSL_self_test,
};
